name: Update

on:
  workflow_dispatch:
    inputs:
      wash_version:
        description: "Version of wash, without the `v`, to release to chocolatey"
        required: true
        default: "0.18.0"
jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Formula
        env:
          WASMCLOUD_URL: https://github.com/wasmCloud/wasmCloud/releases/download/wash-cli-v${{ inputs.wash_version}}/wash-x86_64-pc-windows-msvc.exe
        run: |
          wasmcloud_url=$WASMCLOUD_URL
          wasmcloud_sha=$(curl -sL $WASMCLOUD_URL | shasum -a 256 | cut -d ' ' -f 1 | tr '[:lower:]' '[:upper:]')
          wasmcloud_version=${{ inputs.wash_version }}

          cat ./template/chocolateyinstall.txt | sed "s|WASMCLOUD_URL|$wasmcloud_url|" | sed "s|WASMCLOUD_SHA|$wasmcloud_sha|" > tools/chocolateyinstall.ps1
          cat ./template/wash.txt | sed "s|WASMCLOUD_VERSION|$wasmcloud_version|" > wash.nuspec
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: bump wash to v${{ inputs.wash_version }}
          title: wash v${{ inputs.wash_version }}
          body: This is the release of wash v${{ inputs.wash_version }}. Once tests pass properly, simply merge and then cut a tag from `main` for this version.
          branch: release/v${{ inputs.wash_version }}
          signoff: true
